version: "3.8"
services:
  spark:
    image: bitnami/spark:3.2.1
    ports:
      - "4040:4040"
    volumes:
      - ./data:/data
      - ./scripts:/app
    command: ["spark-submit", "/app/process_data.py", "--input_dir", "/data/bookings"]
